In [ ]:
import pandas as pd 
from pathlib import Path

In [ ]:
# Carga de datos
ruta_actual = Path().resolve()
ruta_proyecto = ruta_actual.parent

RAW_PATH = ruta_proyecto / "data" / "raw" / "Lima_properties_raw.csv" 
PROCESSED_PATH = ruta_proyecto / "data" / "processed" / "lima_properties_clean.csv"

PROCESSED_PATH.parent.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(RAW_PATH)

print(f"Los registros originales son {len(df)}")

df.head(10)

Los registros originales son 4018

,listing_id,listing_url,scraping_date,district_scraped,source,price_pen,price_usd,maintenance_fee,area_total,bedrooms,bathrooms,parking_spaces,address,district,urbanization,photos_count,json_name
0,149387506,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,759000.0,220000.0,NaN,194.0,4.0,3.0,1.0,Edificio Sabadell con Badajoz,Ate Vitarte,Mayorazgo,10,Departamento · 174m² · 4 Dormitorios · 1 Estac...
1,148003136,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,725000.0,NaN,NaN,124.0,3.0,3.0,NaN,Los Olmos Salamanca de Monterrico,Ate Vitarte,Salamanca De Monterrico,10,Departamento · 84m² · 3 Dormitorios
2,149149198,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,404168.0,120000.0,NaN,126.0,3.0,2.0,NaN,Av. Marginal al 100,Ate Vitarte,Javier Prado Et.6,10,Departamento · 126m² · 3 Dormitorios
3,148288992,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,463500.0,133000.0,100.0,107.0,3.0,2.0,NaN,Salamanca de Monterrico,Ate Vitarte,Salamanca De Monterrico,1,Departamento · 107m² · 3 Dormitorios
4,149365027,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,720000.0,210000.0,120.0,136.0,3.0,3.0,1.0,Salamanca de Monterrico,Ate Vitarte,Salamanca De Monterrico,1,Departamento · 115m² · 3 Dormitorios · 1 Estac...
5,145779160,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,482330.0,139000.0,NaN,99.0,3.0,2.0,NaN,C. Marbella al 200,Ate Vitarte,Mayorazgo,1,Departamento · 99m² · 3 Dormitorios
6,147856897,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,450000.0,120000.0,NaN,126.0,4.0,3.0,1.0,Prolongacion Javier Prado Este 9132,Ate Vitarte,Los Portales De Javier Prado,1,Departamento · 126ha · 4 Dormitorios · 1 Estac...
7,147904279,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,530100.0,155000.0,100.0,143.0,3.0,3.0,NaN,Lerida 211 al 200,Ate Vitarte,Mayorazgo,1,Departamento · 143m² · 3 Dormitorios
8,147856000,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,684560.0,199000.0,NaN,372.0,3.0,2.0,2.0,Jr. Juan Jose Crespo al 100,Lima,Ate Vitarte,1,Departamento · 247m² · 3 Dormitorios · 2 Estac...
9,149037885,https://urbania.pe/inmueble/clasificado/veclap...,2026-05-18,ate,urbania,705600.0,210000.0,NaN,270.0,5.0,4.0,NaN,Av. Prol. Javier Prado Este 9051 al 9000,Lima,Ate Vitarte,1,Departamento · 270m² · 5 Dormitorios

In [ ]:
#Tratamiento de datos

#Eliminacion de duplicados
df = df.drop_duplicates(subset = ["listing_id"])

df.columns

Index(['listing_id', 'listing_url', 'scraping_date', 'district_scraped',
       'source', 'price_pen', 'price_usd', 'maintenance_fee', 'area_total',
       'bedrooms', 'bathrooms', 'parking_spaces', 'address', 'district',
       'urbanization', 'photos_count', 'json_name'],
      dtype='str')

In [ ]:
# Visualizando el tipo de dato
print(df.dtypes)
print("\n")
print(df.isnull().sum())

listing_id            int64
listing_url             str
scraping_date           str
district_scraped        str
source                  str
price_pen           float64
price_usd           float64
maintenance_fee     float64
area_total          float64
bedrooms            float64
bathrooms           float64
parking_spaces      float64
address                 str
district                str
urbanization            str
photos_count          int64
json_name               str
dtype: object


listing_id             0
listing_url            0
scraping_date          0
district_scraped       0
source                 0
price_pen             15
price_usd            700
maintenance_fee     2091
area_total             2
bedrooms              52
bathrooms             48
parking_spaces      1907
address                0
district               0
urbanization           0
photos_count           0
json_name              0
dtype: int64

In [ ]:
#Eliminando columnas que no aportan señal predictiva
columnas_no_predictivas = ['listing_url', 'scraping_date', 'source', 'price_usd', 'json_name']
df = df.drop(columnas_no_predictivas, axis =1)

print(f"Las columnas restantes son {df.shape[1]}")
print(df.columns.to_list())

Las columnas restantes son 12
['listing_id', 'district_scraped', 'price_pen', 'maintenance_fee', 'area_total', 'bedrooms', 'bathrooms', 'parking_spaces', 'address', 'district', 'urbanization', 'photos_count']

In [ ]:
#Eliminando columnas
df = df.drop("district", axis = 1)

#Renombrando columnas
dic = {
    "district_scraped" : "district"
}
df = df.rename(dic, axis = 1)

df

,listing_id,district,price_pen,maintenance_fee,area_total,bedrooms,bathrooms,parking_spaces,address,urbanization,photos_count
0,149387506,ate,759000.0,NaN,194.0,4.0,3.0,1.0,Edificio Sabadell con Badajoz,Mayorazgo,10
1,148003136,ate,725000.0,NaN,124.0,3.0,3.0,NaN,Los Olmos Salamanca de Monterrico,Salamanca De Monterrico,10
2,149149198,ate,404168.0,NaN,126.0,3.0,2.0,NaN,Av. Marginal al 100,Javier Prado Et.6,10
3,148288992,ate,463500.0,100.0,107.0,3.0,2.0,NaN,Salamanca de Monterrico,Salamanca De Monterrico,1
4,149365027,ate,720000.0,120.0,136.0,3.0,3.0,1.0,Salamanca de Monterrico,Salamanca De Monterrico,1
...,...,...,...,...,...,...,...,...,...,...,...
4013,147048038,surquillo,528000.0,NaN,69.0,2.0,2.0,1.0,Aramburu,Surquillo,1
4014,149834946,surquillo,425000.0,280.0,72.0,3.0,2.0,1.0,"Avenida Angamos Este, Surquillo",Surquillo,1
4015,145799315,surquillo,432000.0,380.0,54.0,1.0,1.0,1.0,mayor arce de la oliva 737,Surquillo,1
4016,149497049,surquillo,813100.0,460.0,140.0,2.0,2.0,1.0,Calle Lola Pardo Vargas,Barrio Medico,1
4017,147683337,surquillo,257000.0,NaN,37.0,1.0,1.0,1.0,"Av Angamos Este N° 17xx, Dpto. 313 AL 2813",Surquillo,1

In [ ]:
#Filtrando outliers area total

print(df["area_total"].describe())

print(f"\nValores fuera de rango (< 20 o >1000): {((df['area_total']<20) | (df['area_total']>1000)).sum()}")

count      4016.000000
mean        199.991783
std        3903.269327
min          19.000000
25%          66.000000
50%          90.000000
75%         140.000000
max      246080.000000
Name: area_total, dtype: float64

Valores fuera de rango (< 20 o >1000): 16

In [ ]:
mask = ~((df["area_total"]<20)|(df["area_total"]>1000))
df = df[mask]

print(f"La cantidad de filas es {len(df)}")

La cantidad de filas es 4002

In [ ]:
#Tratammiento de NaNs parking_spaces y maintenance_fee (ausencia de valor quiere decir que no tienen esa propiedad)

df["maintenance_fee"] = df["maintenance_fee"].fillna(0)
df["parking_spaces"] = df["parking_spaces"].fillna(0)

df.isna().sum()

listing_id          0
district            0
price_pen          15
maintenance_fee     0
area_total          2
bedrooms           52
bathrooms          48
parking_spaces      0
address             0
urbanization        0
photos_count        0
dtype: int64

In [ ]:
#Nuestro target es el precio, en el target nunca se imputa, por lo que eliminaresmos los nan
df= df.dropna(subset = ["price_pen"])
len(df)

3987

In [ ]:
print(df.groupby("district")["area_total"].count().sort_values())
#Dataset desbalanceado, para futuro recolectar datos de otros portales
#Tomar en consideracion que probablemente haya departamentos duplicados por lo que no se podrá

district
magdalena-del-mar          19
ate                        30
san-juan-de-lurigancho     83
comas                      86
brena                     100
san-martin-de-porres      145
los-olivos                147
la-victoria               162
santiago-de-surco         217
lince                     250
miraflores                255
la-molina                 256
chorrillos                267
san-miguel                268
san-isidro                272
pueblo-libre              276
barranco                  283
surquillo                 288
san-borja                 290
jesus-maria               291
Name: area_total, dtype: int64

In [ ]:
df["area_total"] = df["area_total"].fillna(
    df.groupby("district")["area_total"].transform("median")
)

df["bedrooms"] = df["bedrooms"].fillna(
    df.groupby("district")["bedrooms"].transform("median")
)

df["bathrooms"] = df["bathrooms"].fillna(
    df.groupby("district")["bathrooms"].transform("median")
)
df.isnull().sum()

listing_id         0
district           0
price_pen          0
maintenance_fee    0
area_total         0
bedrooms           0
bathrooms          0
parking_spaces     0
address            0
urbanization       0
photos_count       0
dtype: int64

In [ ]:
# Convirtiendo floats a entero
df["bathrooms"] = df["bathrooms"].astype(int)
df["bedrooms"] = df["bedrooms"].astype(int)
df["parking_spaces"] = df["parking_spaces"].astype(int)

df.info()

<class 'pandas.DataFrame'>
Index: 3987 entries, 0 to 4017
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       3987 non-null   int64
 1   district         3987 non-null   str
 2   price_pen        3987 non-null   float64
 3   maintenance_fee  3987 non-null   float64
 4   area_total       3987 non-null   float64
 5   bedrooms         3987 non-null   int64
 6   bathrooms        3987 non-null   int64
 7   parking_spaces   3987 non-null   int64
 8   address          3987 non-null   str
 9   urbanization     3987 non-null   str
 10  photos_count     3987 non-null   int64
dtypes: float64(3), int64(5), str(3)
memory usage: 373.8 KB

In [ ]:
df.to_csv(PROCESSED_PATH,index=False, encoding="utf-8-sig" )
from pathlib import Path
print(f"Archivo guardado en: {PROCESSED_PATH}")
print(f"Existe: {PROCESSED_PATH.exists()}")
print(f"Tamaño: {PROCESSED_PATH.stat().st_size / 1024:.1f} KB")

Archivo guardado en: C:\Users\USUARIO\OneDrive\Documentos\data_science\lima-real-estate-price-predictor\data\processed\lima_properties_clean.csv
Existe: True
Tamaño: 350.6 KB